language: cpp
sudo: required
addons:
 apt:
  packages:
   - libxml2-dev 
   - libusb-1.0-0-dev
   - libcurl4-openssl-dev
   - libgtest-dev
   - gcov
before_script:
 - cp -r /usr/src/gtest gtest
 - cd gtest
 - cmake . 
 - make 
 - sudo mv libg* /usr/lib/ 
 - cd - 
script: make debug
